### ISSUE TITLE
Deploying notebooks task cannot find path to py file in Agent.BuildDirectory ?

### ISSUE THREAD

**Issue by mcalnd70** [DataThirstLtd/databricks.vsts.tools#44]
I have an issue with the task: DataThirstLtd.databricksDeployScriptsTasks.databricksDeployScriptsTask.databricksDeployScripts@0

This is my AZDO YAML pipeline (my repo is called "MyTestRepo")

```
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - notebooks

stages:
- stage: "DEV"
  displayName: "DEV"
  dependsOn: []
  variables:
    - name: adbnotebook01
      value: 'MyNotebook.py'
  jobs:
    - deployment: DEV
      displayName: 'DEV01'
      pool:
        vmImage: "windows-latest"    
      environment: 'ENV_DEV' # !CHANGE! ENV - used for Approval Groups in AZDO
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                path: MyTestRepo
              # Find py file  
              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: 'Get-ChildItem -Path $(Agent.BuildDirectory)/MyTestRepo/notebooks/Shared/$(adbnotebook01)'
              # Deploy py file                  
              - task: DataThirstLtd.databricksDeployScriptsTasks.databricksDeployScriptsTask.databricksDeployScripts@0
                displayName: 'Databricks Notebooks deployment for $(adbnotebook01)'
                inputs:
                  authMethod: servicePrincipal
                  applicationId: redacted
                  spSecret: redacted
                  resourceGroup: redacted
                  workspace: redacted
                  subscriptionId: redacted
                  tenantId: redacted
                  localPath: '$(Agent.BuildDirectory)/MyTestRepo/notebooks/Shared/$(adbnotebook01)'
                  databricksPath: /Shared

```
When the Powershell task in-line script runs to check the contents of the $(Agent.BuildDirectory) it reports...

```
    Directory: D:\a\1\MyTestRepo\notebooks\Shared


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        4/23/2021  10:20 AM          22583 MyNotebook.py
```

When the Databricks task runs it reports...

```
==============================================================================
Task         : Databricks Deploy Notebooks
Description  : Deploys a folder of Notebooks to your Databricks workspace
Version      : 0.9.2916
Author       : Data Thirst Ltd
Help         : 
==============================================================================
Tools Version: 2.1.2915
Connecting via AAD
Clean false
Running without clean
##[error]Cannot find path 'D:\a\1\MyTestRepo\notebooks\Shared\MyNotebook.py' because it does not exist.
```

I don't understand why this is. Is this task not allowed to read the $(Agent.BuildDirectory) path?
